[package]
name = "wikidata"
version = "0.1.0"
authors = ["Radu Popescu <mail@radupopescu.net>"]

[dependencies]
clap = "~2.19.0"
serde = "0.8"
serde_json = "0.8"
flate2 = { version = "0.2", features = ["zlib"], default-features = false }
time = "0.1.35"
futures = "0.1"
futures-cpupool = "0.1"
